# See http://jekyllrb.com/docs/configuration/.
name: Conseil d'Architecture, d'Urbanisme et de l'Environnement de Dordogne
# GitHub Pages is running in safe mode, so use it during tests as well.
safe: true
# No permalink
permalink: none
# Prose-related configuration
# See https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: "http://makinacorpus.github.io/caue24"
  media: "assets/images"
  metadata:
    _posts/features:
      - name: title
        field:
          element: text
          label: Titre
          value: "Ecrivez ici le titre de la popup"
      - name: popup
        field:
          element: textarea
          label: Texte de la popup
          value: "Ecrivez ici le texte s'affichant en popup, laisser vide pour ne pas déclencher de popup"
      - name: additionnal
        field:
          element: textarea
          label: Texte additionnel
          value: "Ecrivez ici le texte additionnel s'affichant sous la carte à gauche, laisser vide pour ne rien afficher"
      - name: slideshow
        field:
          element: textarea
          label: Diaporama
          value: "Insérez ici les images que vous voulez afficher dans le diaporama, laisser vide pour ne déclencher aucun diaporama"
      - name: layout
        field:
          element: hidden
          value: feature
    _posts/pages:
      - name: communaute
        field:
          label: Communauté de Communes
          element: select
          placeholder: Sélectionnez une communauté de communes
          options:
            - name: com1
              value: Communauté de commune 1
            - name: com2
              value: Communauté de commune 2
            - name: com3
              value: Communauté de commune 3
            - name: com4
              value: Communauté de commune 4
            - name: com5
              value: Communauté de commune 5
      - name: type
        field:
          label: Type de page
          element: select
          placeholder: Sélectionnez un type de page
          options:
            - name: portrait
              value: Portrait
            - name: geographie
              value: Géographie
            - name: histoire
              value: Histoire
            - name: urbanisme
              value: Urbanisme
            - name: architecture
              value: Architecture
            - name: atouts
              value: Atouts
      - name: layout
        field:
          element: hidden
          value: communaute
