# See http://jekyllrb.com/docs/configuration/.
name: Conseil d'Architecture, d'Urbanisme et de l'Environnement de Dordogne
# GitHub Pages is running in safe mode, so use it during tests as well.
safe: true
# No permalink
permalink: none
# Currently using github project domain
root: /caue24
# Exclude some files we don't want in the site
exclude:
  - README.md
  - .gitignore
  - .gitlab-ci.yml
  - node_modules
  - package*
  - e2e
# Markdown interpreter
markdown: kramdown
# prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: "http://makinacorpus.github.io/caue24"
  media: "data/images"
  rooturl: "data"
  metadata:
    "data":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
